name: 🐛 Багрепорт
description: Сообщить об ошибке в приложении Offline Notes
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Спасибо за сообщение об ошибке! Пожалуйста, заполните форму ниже, чтобы мы могли лучше понять проблему.

  - type: dropdown
    id: bug-type
    attributes:
      label: Тип ошибки
      description: Выберите тип ошибки
      options:
        - Критическая ошибка (приложение не запускается/крашится)
        - Функциональная ошибка (функция работает неправильно)
        - Ошибка интерфейса (UI/UX проблема)
        - Ошибка производительности
        - Ошибка данных (потеря/повреждение заметок)
        - Другое
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Описание ошибки
      description: Четко и подробно опишите, что произошло
      placeholder: Опишите, что вы ожидали и что произошло на самом деле
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Шаги для воспроизведения
      description: Пошаговые инструкции для воспроизведения ошибки
      placeholder: |
        1. Откройте приложение
        2. Нажмите на...
        3. Прокрутите до...
        4. Ошибка происходит
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Ожидаемое поведение
      description: Что должно было произойти?
      placeholder: Опишите, что вы ожидали увидеть
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Фактическое поведение
      description: Что произошло на самом деле?
      placeholder: Опишите, что произошло вместо ожидаемого
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Серьезность ошибки
      description: Насколько критична эта ошибка?
      options:
        - Критическая (приложение не работает)
        - Высокая (основная функциональность нарушена)
        - Средняя (функциональность частично нарушена)
        - Низкая (незначительная проблема)
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: Версия приложения
      description: Какая версия приложения установлена?
      placeholder: например, 1.0.0
    validations:
      required: true

  - type: dropdown
    id: android-version
    attributes:
      label: Версия Android
      description: Какая версия Android установлена на устройстве?
      options:
        - Android 14 (API 34)
        - Android 13 (API 33)
        - Android 12 (API 31-32)
        - Android 11 (API 30)
        - Android 10 (API 29)
        - Android 9 (API 28)
        - Android 8 (API 26-27)
        - Другое
    validations:
      required: true

  - type: input
    id: device-model
    attributes:
      label: Модель устройства
      description: Какая модель устройства?
      placeholder: например, Samsung Galaxy S23, Pixel 7, Xiaomi Redmi Note 12
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Логи/Скриншоты
      description: Приложите логи, скриншоты или видео, если возможно
      placeholder: |
        Если у вас есть логи из logcat или скриншоты ошибки, приложите их здесь.
        
        Для получения логов:
        1. Включите режим разработчика
        2. Используйте adb logcat или приложение для просмотра логов
        3. Воспроизведите ошибку
        4. Скопируйте соответствующие логи

  - type: textarea
    id: additional-context
    attributes:
      label: Дополнительная информация
      description: Любая другая информация, которая может помочь
      placeholder: |
        - Происходит ли ошибка постоянно или только иногда?
        - Была ли эта функция работала раньше?
        - Есть ли другие приложения, которые могут влиять на работу?
        - Любые другие детали, которые могут быть полезны

  - type: checkboxes
    id: terms
    attributes:
      label: Подтверждение
      description: Пожалуйста, подтвердите следующее
      options:
        - label: Я проверил, что эта ошибка еще не была зарегистрирована
          required: true
        - label: Я предоставил всю необходимую информацию для воспроизведения ошибки
          required: true
        - label: Я готов предоставить дополнительную информацию при необходимости
          required: true
