blank_issues_enabled: false
contact_links:
  - name: 🐛 Багрепорты
    url: https://github.com/light-for-bright/Offline-Notes/issues/new?template=bug_report.yml
    about: Сообщить об ошибке в приложении
  - name: ✨ Предложения функций
    url: https://github.com/light-for-bright/Offline-Notes/issues/new?template=feature_request.yml
    about: Предложить новую функцию
