name: ✨ Предложение функции
description: Предложить новую функцию для приложения Offline Notes
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Спасибо за предложение новой функции! Пожалуйста, заполните форму ниже, чтобы мы могли лучше понять вашу идею.

  - type: dropdown
    id: feature-type
    attributes:
      label: Тип функции
      description: К какой категории относится ваше предложение?
      options:
        - Новый функционал (создание/редактирование заметок)
        - Улучшение интерфейса (UI/UX)
        - Интеграция с внешними сервисами
        - Настройки и конфигурация
        - Экспорт/импорт данных
        - Безопасность и приватность
        - Производительность
        - Доступность
        - Другое
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Описание функции
      description: Четко и подробно опишите предлагаемую функцию
      placeholder: Опишите, что должна делать новая функция и как она должна работать
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Проблема, которую решает функция
      description: Какую проблему или потребность решает эта функция?
      placeholder: |
        Опишите:
        - Какую проблему вы пытаетесь решить?
        - Какие ограничения есть в текущей версии?
        - Почему существующие функции не подходят?
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Предлагаемое решение
      description: Как вы видите реализацию этой функции?
      placeholder: |
        Опишите:
        - Как должна работать новая функция?
        - Где в интерфейсе она должна располагаться?
        - Какие настройки должны быть доступны?
        - Как пользователь будет взаимодействовать с функцией?
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Приоритет
      description: Насколько важна эта функция для вас?
      options:
        - Критически важно (не могу использовать приложение без этого)
        - Очень важно (значительно улучшит опыт использования)
        - Важно (будет полезно иметь)
        - Желательно (приятно было бы иметь)
        - Не важно (просто идея)
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: Тип пользователя
      description: Кто вы?
      options:
        - Обычный пользователь
        - Студент/преподаватель
        - Профессионал (бизнес)
        - Разработчик
        - Другое
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Сценарии использования
      description: Опишите конкретные ситуации, где эта функция будет полезна
      placeholder: |
        Например:
        - "Когда я делаю заметки на лекции, мне нужно..."
        - "При работе с большими документами я хочу..."
        - "Для организации заметок по проектам я бы использовал..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Альтернативные решения
      description: Рассматривали ли вы другие способы решения этой проблемы?
      placeholder: |
        - Использовали ли вы другие приложения для этой задачи?
        - Есть ли обходные пути в текущей версии?
        - Какие альтернативы вы рассматривали?
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Мокапы/Скриншоты
      description: Если у вас есть наброски, мокапы или примеры из других приложений
      placeholder: |
        Приложите изображения, если у вас есть:
        - Наброски интерфейса
        - Примеры из других приложений
        - Мокапы или прототипы
        - Любые визуальные материалы, которые помогут понять идею

  - type: textarea
    id: additional-context
    attributes:
      label: Дополнительная информация
      description: Любая другая информация, которая может быть полезна
      placeholder: |
        - Есть ли похожие функции в других приложениях для заметок?
        - Какие технические ограничения нужно учесть?
        - Влияет ли это на производительность или размер приложения?
        - Нужны ли дополнительные разрешения?
        - Любые другие соображения

  - type: checkboxes
    id: terms
    attributes:
      label: Подтверждение
      description: Пожалуйста, подтвердите следующее
      options:
        - label: Я проверил, что эта функция еще не была предложена
          required: true
        - label: Я готов участвовать в обсуждении и тестировании функции
          required: true
        - label: Я понимаю, что не все предложения могут быть реализованы
          required: true
